/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sample.thing.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SampleThing service. Represents a row in the &quot;Sample_SampleThing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link sample.thing.model.impl.SampleThingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link sample.thing.model.impl.SampleThingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SampleThing
 * @see sample.thing.model.impl.SampleThingImpl
 * @see sample.thing.model.impl.SampleThingModelImpl
 * @generated
 */
@ProviderType
public interface SampleThingModel extends BaseModel<SampleThing>, GroupedModel,
	ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sample thing model instance should use the {@link SampleThing} interface instead.
	 */

	/**
	 * Returns the primary key of this sample thing.
	 *
	 * @return the primary key of this sample thing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sample thing.
	 *
	 * @param primaryKey the primary key of this sample thing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sample thing.
	 *
	 * @return the uuid of this sample thing
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this sample thing.
	 *
	 * @param uuid the uuid of this sample thing
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sample ID of this sample thing.
	 *
	 * @return the sample ID of this sample thing
	 */
	public long getSampleId();

	/**
	 * Sets the sample ID of this sample thing.
	 *
	 * @param sampleId the sample ID of this sample thing
	 */
	public void setSampleId(long sampleId);

	/**
	 * Returns the group ID of this sample thing.
	 *
	 * @return the group ID of this sample thing
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this sample thing.
	 *
	 * @param groupId the group ID of this sample thing
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this sample thing.
	 *
	 * @return the company ID of this sample thing
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sample thing.
	 *
	 * @param companyId the company ID of this sample thing
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this sample thing.
	 *
	 * @return the user ID of this sample thing
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this sample thing.
	 *
	 * @param userId the user ID of this sample thing
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sample thing.
	 *
	 * @return the user uuid of this sample thing
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this sample thing.
	 *
	 * @param userUuid the user uuid of this sample thing
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this sample thing.
	 *
	 * @return the user name of this sample thing
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this sample thing.
	 *
	 * @param userName the user name of this sample thing
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this sample thing.
	 *
	 * @return the create date of this sample thing
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this sample thing.
	 *
	 * @param createDate the create date of this sample thing
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sample thing.
	 *
	 * @return the modified date of this sample thing
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sample thing.
	 *
	 * @param modifiedDate the modified date of this sample thing
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this sample thing.
	 *
	 * @return the status of this sample thing
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this sample thing.
	 *
	 * @param status the status of this sample thing
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this sample thing.
	 *
	 * @return the status by user ID of this sample thing
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this sample thing.
	 *
	 * @param statusByUserId the status by user ID of this sample thing
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this sample thing.
	 *
	 * @return the status by user uuid of this sample thing
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this sample thing.
	 *
	 * @param statusByUserUuid the status by user uuid of this sample thing
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this sample thing.
	 *
	 * @return the status by user name of this sample thing
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this sample thing.
	 *
	 * @param statusByUserName the status by user name of this sample thing
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this sample thing.
	 *
	 * @return the status date of this sample thing
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this sample thing.
	 *
	 * @param statusDate the status date of this sample thing
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the some string of this sample thing.
	 *
	 * @return the some string of this sample thing
	 */
	@AutoEscape
	public String getSomeString();

	/**
	 * Sets the some string of this sample thing.
	 *
	 * @param someString the some string of this sample thing
	 */
	public void setSomeString(String someString);

	/**
	 * Returns the some boolean of this sample thing.
	 *
	 * @return the some boolean of this sample thing
	 */
	public boolean getSomeBoolean();

	/**
	 * Returns <code>true</code> if this sample thing is some boolean.
	 *
	 * @return <code>true</code> if this sample thing is some boolean; <code>false</code> otherwise
	 */
	public boolean isSomeBoolean();

	/**
	 * Sets whether this sample thing is some boolean.
	 *
	 * @param someBoolean the some boolean of this sample thing
	 */
	public void setSomeBoolean(boolean someBoolean);

	/**
	 * Returns the some int of this sample thing.
	 *
	 * @return the some int of this sample thing
	 */
	public int getSomeInt();

	/**
	 * Sets the some int of this sample thing.
	 *
	 * @param someInt the some int of this sample thing
	 */
	public void setSomeInt(int someInt);

	/**
	 * Returns the some date of this sample thing.
	 *
	 * @return the some date of this sample thing
	 */
	public Date getSomeDate();

	/**
	 * Sets the some date of this sample thing.
	 *
	 * @param someDate the some date of this sample thing
	 */
	public void setSomeDate(Date someDate);

	/**
	 * Returns <code>true</code> if this sample thing is approved.
	 *
	 * @return <code>true</code> if this sample thing is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this sample thing is denied.
	 *
	 * @return <code>true</code> if this sample thing is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this sample thing is a draft.
	 *
	 * @return <code>true</code> if this sample thing is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this sample thing is expired.
	 *
	 * @return <code>true</code> if this sample thing is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this sample thing is inactive.
	 *
	 * @return <code>true</code> if this sample thing is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this sample thing is incomplete.
	 *
	 * @return <code>true</code> if this sample thing is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this sample thing is pending.
	 *
	 * @return <code>true</code> if this sample thing is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this sample thing is scheduled.
	 *
	 * @return <code>true</code> if this sample thing is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SampleThing sampleThing);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SampleThing> toCacheModel();

	@Override
	public SampleThing toEscapedModel();

	@Override
	public SampleThing toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}