/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sample.thing.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import sample.thing.model.SampleThing;
import sample.thing.model.SampleThingModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SampleThing service. Represents a row in the &quot;Sample_SampleThing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SampleThingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SampleThingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SampleThingImpl
 * @see SampleThing
 * @see SampleThingModel
 * @generated
 */
@ProviderType
public class SampleThingModelImpl extends BaseModelImpl<SampleThing>
	implements SampleThingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sample thing model instance should use the {@link SampleThing} interface instead.
	 */
	public static final String TABLE_NAME = "Sample_SampleThing";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "sampleId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP },
			{ "someString", Types.VARCHAR },
			{ "someBoolean", Types.BOOLEAN },
			{ "someInt", Types.INTEGER },
			{ "someDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sampleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("someString", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("someBoolean", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("someInt", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("someDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table Sample_SampleThing (uuid_ VARCHAR(75) null,sampleId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,someString VARCHAR(75) null,someBoolean BOOLEAN,someInt INTEGER,someDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Sample_SampleThing";
	public static final String ORDER_BY_JPQL = " ORDER BY sampleThing.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Sample_SampleThing.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(sample.thing.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.sample.thing.model.SampleThing"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(sample.thing.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.sample.thing.model.SampleThing"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(sample.thing.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.sample.thing.model.SampleThing"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long SOMESTRING_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(sample.thing.service.util.ServiceProps.get(
				"lock.expiration.time.sample.thing.model.SampleThing"));

	public SampleThingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sampleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSampleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sampleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SampleThing.class;
	}

	@Override
	public String getModelClassName() {
		return SampleThing.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("sampleId", getSampleId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());
		attributes.put("someString", getSomeString());
		attributes.put("someBoolean", getSomeBoolean());
		attributes.put("someInt", getSomeInt());
		attributes.put("someDate", getSomeDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long sampleId = (Long)attributes.get("sampleId");

		if (sampleId != null) {
			setSampleId(sampleId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}

		String someString = (String)attributes.get("someString");

		if (someString != null) {
			setSomeString(someString);
		}

		Boolean someBoolean = (Boolean)attributes.get("someBoolean");

		if (someBoolean != null) {
			setSomeBoolean(someBoolean);
		}

		Integer someInt = (Integer)attributes.get("someInt");

		if (someInt != null) {
			setSomeInt(someInt);
		}

		Date someDate = (Date)attributes.get("someDate");

		if (someDate != null) {
			setSomeDate(someDate);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getSampleId() {
		return _sampleId;
	}

	@Override
	public void setSampleId(long sampleId) {
		_sampleId = sampleId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public String getSomeString() {
		if (_someString == null) {
			return StringPool.BLANK;
		}
		else {
			return _someString;
		}
	}

	@Override
	public void setSomeString(String someString) {
		_columnBitmask |= SOMESTRING_COLUMN_BITMASK;

		if (_originalSomeString == null) {
			_originalSomeString = _someString;
		}

		_someString = someString;
	}

	public String getOriginalSomeString() {
		return GetterUtil.getString(_originalSomeString);
	}

	@Override
	public boolean getSomeBoolean() {
		return _someBoolean;
	}

	@Override
	public boolean isSomeBoolean() {
		return _someBoolean;
	}

	@Override
	public void setSomeBoolean(boolean someBoolean) {
		_someBoolean = someBoolean;
	}

	@Override
	public int getSomeInt() {
		return _someInt;
	}

	@Override
	public void setSomeInt(int someInt) {
		_someInt = someInt;
	}

	@Override
	public Date getSomeDate() {
		return _someDate;
	}

	@Override
	public void setSomeDate(Date someDate) {
		_someDate = someDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				SampleThing.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SampleThing.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SampleThing toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SampleThing)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SampleThingImpl sampleThingImpl = new SampleThingImpl();

		sampleThingImpl.setUuid(getUuid());
		sampleThingImpl.setSampleId(getSampleId());
		sampleThingImpl.setGroupId(getGroupId());
		sampleThingImpl.setCompanyId(getCompanyId());
		sampleThingImpl.setUserId(getUserId());
		sampleThingImpl.setUserName(getUserName());
		sampleThingImpl.setCreateDate(getCreateDate());
		sampleThingImpl.setModifiedDate(getModifiedDate());
		sampleThingImpl.setStatus(getStatus());
		sampleThingImpl.setStatusByUserId(getStatusByUserId());
		sampleThingImpl.setStatusByUserName(getStatusByUserName());
		sampleThingImpl.setStatusDate(getStatusDate());
		sampleThingImpl.setSomeString(getSomeString());
		sampleThingImpl.setSomeBoolean(getSomeBoolean());
		sampleThingImpl.setSomeInt(getSomeInt());
		sampleThingImpl.setSomeDate(getSomeDate());

		sampleThingImpl.resetOriginalValues();

		return sampleThingImpl;
	}

	@Override
	public int compareTo(SampleThing sampleThing) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), sampleThing.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SampleThing)) {
			return false;
		}

		SampleThing sampleThing = (SampleThing)obj;

		long primaryKey = sampleThing.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SampleThingModelImpl sampleThingModelImpl = this;

		sampleThingModelImpl._originalUuid = sampleThingModelImpl._uuid;

		sampleThingModelImpl._originalGroupId = sampleThingModelImpl._groupId;

		sampleThingModelImpl._setOriginalGroupId = false;

		sampleThingModelImpl._originalCompanyId = sampleThingModelImpl._companyId;

		sampleThingModelImpl._setOriginalCompanyId = false;

		sampleThingModelImpl._setModifiedDate = false;

		sampleThingModelImpl._originalSomeString = sampleThingModelImpl._someString;

		sampleThingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SampleThing> toCacheModel() {
		SampleThingCacheModel sampleThingCacheModel = new SampleThingCacheModel();

		sampleThingCacheModel.uuid = getUuid();

		String uuid = sampleThingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			sampleThingCacheModel.uuid = null;
		}

		sampleThingCacheModel.sampleId = getSampleId();

		sampleThingCacheModel.groupId = getGroupId();

		sampleThingCacheModel.companyId = getCompanyId();

		sampleThingCacheModel.userId = getUserId();

		sampleThingCacheModel.userName = getUserName();

		String userName = sampleThingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			sampleThingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			sampleThingCacheModel.createDate = createDate.getTime();
		}
		else {
			sampleThingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sampleThingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			sampleThingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		sampleThingCacheModel.status = getStatus();

		sampleThingCacheModel.statusByUserId = getStatusByUserId();

		sampleThingCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = sampleThingCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			sampleThingCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			sampleThingCacheModel.statusDate = statusDate.getTime();
		}
		else {
			sampleThingCacheModel.statusDate = Long.MIN_VALUE;
		}

		sampleThingCacheModel.someString = getSomeString();

		String someString = sampleThingCacheModel.someString;

		if ((someString != null) && (someString.length() == 0)) {
			sampleThingCacheModel.someString = null;
		}

		sampleThingCacheModel.someBoolean = getSomeBoolean();

		sampleThingCacheModel.someInt = getSomeInt();

		Date someDate = getSomeDate();

		if (someDate != null) {
			sampleThingCacheModel.someDate = someDate.getTime();
		}
		else {
			sampleThingCacheModel.someDate = Long.MIN_VALUE;
		}

		return sampleThingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", sampleId=");
		sb.append(getSampleId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append(", someString=");
		sb.append(getSomeString());
		sb.append(", someBoolean=");
		sb.append(getSomeBoolean());
		sb.append(", someInt=");
		sb.append(getSomeInt());
		sb.append(", someDate=");
		sb.append(getSomeDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("sample.thing.model.SampleThing");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sampleId</column-name><column-value><![CDATA[");
		sb.append(getSampleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>someString</column-name><column-value><![CDATA[");
		sb.append(getSomeString());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>someBoolean</column-name><column-value><![CDATA[");
		sb.append(getSomeBoolean());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>someInt</column-name><column-value><![CDATA[");
		sb.append(getSomeInt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>someDate</column-name><column-value><![CDATA[");
		sb.append(getSomeDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = SampleThing.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			SampleThing.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _sampleId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _someString;
	private String _originalSomeString;
	private boolean _someBoolean;
	private int _someInt;
	private Date _someDate;
	private long _columnBitmask;
	private SampleThing _escapedModel;
}